import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useSession} from "@inrupt/solid-ui-react";
import Loading from "@/components/loading";
import LoginForm from "@/components/loginForm";
import LogoutButton from "@/components/logoutButton";

export default function Home() {
    const {sessionRequestInProgress, session} = useSession();
    const {info} = session;
    console.log("SESSION", session);

    if (sessionRequestInProgress) {
        return <Loading />
    }

    if (!info.isLoggedIn) {
        return <LoginForm />
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <h1>test</h1>
                <LogoutButton />
            </main>
        </>
    )
}
