import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {LinkedDataObject} from "ldo";
import {TodoList} from "@/ldo/todo.typings";
import {TodoListFactory} from "@/ldo/todo.ldoFactory";

export default function Home() {
    const list: LinkedDataObject<TodoList> = TodoListFactory.new();
    list.listName = "This is my cool todo list";
    console.log(list.$changes());
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <h1>{list.listName}</h1>
                test
            </main>
        </>
    )
}
